version: '3.1'

services:
  app:
    image: nestjs-docker
    container_name: nestjs-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/src/app/nestjs
      - /src/app/nestjs/node_modules