apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
      - name: nest-app
        image: gcr.io/relevans2-bb0f6/nestjssw2:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: nest-env
---
apiVersion: v1
kind: Service
metadata:
  name: nest-svc
spec:
  type: LoadBalancer
  selector:
    app: nest-app
  ports:
  - port: 80
    targetPort: 3000